## Techcareer.Net Veri Bilimine Giriş Kampı Hafta 3 Ödevi Çözümü

## Soru 1

In [3]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]

benzersiz_liste = []
for ognotu in notlar:
    if ognotu not in benzersiz_liste:
        benzersiz_liste.append(ognotu)

# En yüksek ve en düşük not
en_yuksek_not = max(notlar)
en_dusuk_not = min(notlar)

# Küçükten büyüğe sıralama
notlar_sirali = sorted(notlar)

print("Benzersiz notlar:", benzersiz_liste)
print("En yüksek not:", en_yuksek_not)
print("En düşük not:", en_dusuk_not)
print("Küçükten büyüğe sıralı:", notlar_sirali)

Benzersiz notlar: [85, 92, 76, 100]
En yüksek not: 100
En düşük not: 76
Küçükten büyüğe sıralı: [76, 76, 85, 85, 92, 92, 92, 100]


## Soru 2

In [8]:

def armstrong_mu(sayi):
# list comprehension bilgimle yaptım
    sayi_basamak = [int(rakam) for rakam in str(sayi)]
    kup_toplami = sum(rakam**3 for rakam in sayi_basamak)
    return kup_toplami == sayi

sayi = int(input("Bir sayı giriniz:"))

if armstrong_mu(sayi):
    print(sayi, ", bir Armstrong sayısı.")
else:
    print(sayi, ", bir Armstrong sayısı değildir.")

153 ,bir Armstrong sayısı.


## Soru 3

In [9]:

A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

ortak_diller = A & B
sadece_A_dilleri = A - B
küme_birleşimi = sorted(A | B)

print("Ortak diller:", ortak_diller)
print("Sadece A'da olan diller:", sadece_A_dilleri )
print("Birleşim kümesi(alfabetik):", küme_birleşimi)

Ortak diller: {'SQL', 'Python'}
Sadece A'da olan diller: {'Java', 'R'}
Birleşim kümesi(alfabetik): ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


## Soru 4

In [11]:
import random
import statistics as ist
## list comprehension
random_sayilar = [random.randint(1, 100) for a in range(10)]

ortalama = ist.mean(random_sayilar)
standart_sapma = ist.pstdev(random_sayilar)

print("Rastgele sayılar:", random_sayilar)
print("Ortalama:", ortalama)
print("Standart sapma:", standart_sapma)


Rastgele sayılar: [69, 97, 75, 15, 54, 9, 83, 52, 43, 94]
Ortalama: 59.1
Standart sapma: 28.925594203058303


## Soru 5

In [18]:
def kelime_sayaci(metin):
    kelimeler = metin.split()
    toplam = len(kelimeler)
    en_uzun = max(kelimeler, key=len)

    #
    en_sik = max(set(kelimeler), key=kelimeler.count)


    if kelimeler.count(en_sik) < 2:
        en_sik = None

    return toplam, en_uzun, en_sik


metin = input("Bir metin girin: ")

toplam, en_uzun, en_sik = kelime_sayaci(metin)

print("Toplam kelime sayısı:", toplam)
print("En uzun kelime:", en_uzun)
if en_sik:
    print("En sık geçen kelime:", en_sik)
else:
    print("Hiçbir kelime birden fazla geçmiyor.")


Toplam kelime sayısı: 4
En uzun kelime: SENANUR
Hiçbir kelime birden fazla geçmiyor.


## Soru 6 

In [ ]:
sayilar = [5, 12, 7, 18, 24, 3, 16]

cift_sayilar = list(filter(lambda x: x % 2 == 0, sayilar))
kareler = list(map(lambda x: x**2, cift_sayilar))
azalan_kareler = sorted(kareler, reverse=True)

print("Çift Sayılar:", cift_sayilar)
print("Sayıların Kareleri:", kareler)
print("Sayıların karelerinin azalan şekilde sıralanışı:", azalan_kareler)


## Soru 7

In [3]:

kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
kucukten_buyuge = sorted(kelimeler, key= lambda k: len(k) )
print(kucukten_buyuge)


['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


## Soru 8

In [4]:
def rakam_toplami(metin):
    toplam = 0
    for c in metin:
        if c.isdigit():      # karakter bir rakam mı?
            toplam += int(c) # rakamı sayıya çevirip topla
    return toplam

# Kullanıcıdan metin al
metin = input("Bir metin girin: ")

print("Metninizdeki rakamların toplamı:", rakam_toplami(metin))


Rakamların toplamı: 7


## Soru 9

In [8]:

import numpy as np

np.random.seed(42)
dizi = np.random.randint(0, 50, 10)
dizi_ortalama = dizi.mean()
dizi_sapma = dizi.std()
dizi_maksimum = dizi.max()

print("Dizi:", dizi)
print("Ortalama:", dizi_ortalama)
print("Standart sapma:", round(dizi_sapma,2))
print("En büyük değer:", dizi_maksimum)


Dizi: [38 28 14 42  7 20 38 18 22 10]
Ortalama: 23.7
Standart sapma: 11.71
En büyük değer: 42


## Soru 10

In [16]:
import numpy as np


matris = np.random.rand(5, 5)
print("\nOrijinal matris:\n", matris)

sutun_ortalamalari = matris.mean(axis=0)
print("\nHer sütunun ortalaması:\n", sutun_ortalamalari)


binary_matris = (matris > 0.5).astype(int)
print("\nBinary matris:\n", binary_matris)



Orijinal matris:
 [[0.69243603 0.26941233 0.24412552 0.16829104 0.21876422]
 [0.558102   0.40383617 0.06489225 0.25391541 0.24687606]
 [0.69630427 0.71227059 0.14808693 0.99774049 0.26678101]
 [0.97661496 0.41103701 0.03305073 0.34507125 0.63435134]
 [0.68070545 0.53093458 0.44778316 0.55289309 0.59269672]]

Her sütunun ortalaması:
 [0.72083254 0.46549814 0.18758772 0.46358226 0.39189387]

Binary matris:
 [[1 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 1 0]
 [1 0 0 0 1]
 [1 1 0 1 1]]
